author = "Oxalin"
country_code = "GB"
description = "Cross City Line between Birmingham New Street, Redditch and Bromsgrove"
display_name = "Cross City Line (South)"
doc_files = [ "Cross_City_Line_(South).md",]
factual = true
img_files = [ "Cross_City_Line_(South).bmp",]
name = "Cross City Line (South)"
release_date = "2023-07-14"
rly_file = "Cross_City_Line_(South).rly"
ssn_files = [ "Cross_City_Line_(South)_Initial_Session.ssn",]
ttb_files = [ "Cross_City_Line_(South)_06-09-23.ttb",]
version = "1.0.0"
year = 2023
signal_position = "left"
contributors = []
